---

- name: ansible module to install webstack, dns & ntp

  hosts: workers
  user: root
  gather_facts: true
  tasks:

- name: apply common settings
  hosts: workers
  user: root
  tasks:
  roles:
    - common

- name: install and configure apache webservers
  hosts: workers
  user: root
  tasks:
  roles:
    - web
...
